import { useState } from 'react'
import Preloader from '../components/Preloader'
import Hero from '../sections/Hero'
import Marquee from '../sections/Marquee'
import Manifesto from '../sections/Manifesto'
import Works from '../sections/Works'
import Services from '../sections/Services'
import Recognition from '../sections/Recognition'
import Footer from '../sections/Footer'
export default function Home(){const [loaded,setLoaded]=useState(false);return <div className="grain bg-[#0e0e0e] text-[#eae7e0] min-h-screen"><Preloader onDone={()=>setLoaded(true)}/><main><Hero started={loaded}/><Marquee items={['Display','HTML5','Motion','Adaptation','Campaigns','Formats','Production','Delivery']} dark/><Manifesto/><Works/><Marquee items={['Bannermatic','Banner Campaigns','Display Ads','Motion','HTML5','Multi-format','Production']} slow/><Services/><Recognition/></main><Footer/></div>}
